name: text_classification_api
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.0.8
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bzip2=1.0.8
  - ca-certificates=2022.9.14
  - certifi=2022.9.14
  - colorama=0.4.5
  - debugpy=1.6.3
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=1.0.0
  - ipykernel=6.14.0
  - ipython=8.4.0
  - jedi=0.18.1
  - jupyter_client=7.3.5
  - jupyter_core=4.11.1
  - libffi=3.4.2
  - libsodium=1.0.18
  - libsqlite=3.39.2
  - libzlib=1.2.12
  - matplotlib-inline=0.1.6
  - nest-asyncio=1.5.5
  - openssl=1.1.1q
  - packaging=21.3
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=22.1.2
  - prompt-toolkit=3.0.31
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pygments=2.13.0
  - pyparsing=3.0.9
  - python=3.8.13
  - python-dateutil=2.8.2
  - python_abi=3.8
  - setuptools=63.4.1
  - six=1.16.0
  - sqlite=3.39.2
  - stack_data=0.5.0
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.4.0
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.6
  - zeromq=4.3.4
  - pip:
    - altair==4.2.0
    - amqp==5.1.1
    - anyio==3.6.1
    - asgiref==3.5.2
    - astroid==2.12.10
    - attrs==22.1.0
    - auto-labeling-pipeline==0.1.21
    - autocorrect==2.6.1
    - backports-zoneinfo==0.2.1
    - beautifulsoup4==4.11.1
    - billiard==3.6.4.0
    - black==22.8.0
    - blinker==1.5
    - boto3==1.24.80
    - botocore==1.27.80
    - brotli==1.0.9
    - celery==5.2.7
    - cffi==1.15.1
    - chardet==4.0.0
    - charset-normalizer==2.1.1
    - click-didyoumean==0.3.0
    - click-plugins==1.1.1
    - click-repl==0.2.0
    - colorlover==0.3.0
    - commonmark==0.9.1
    - configargparse==1.5.3
    - contourpy==1.0.5
    - coreapi==2.3.3
    - coreschema==0.0.4
    - coverage==6.4.4
    - cssselect==1.1.0
    - cycler==0.11.0
    - cymem==2.0.6
    - defusedxml==0.7.1
    - dj-database-url==0.5.0
    - dj-rest-auth==2.2.5
    - django==4.1.1
    - django-celery-results==2.2.0
    - django-cleanup==6.0.0
    - django-cors-headers==3.13.0
    - django-drf-filepond==0.4.1
    - django-filter==21.1
    - django-health-check==3.17.0
    - django-polymorphic==3.1.0
    - django-rest-polymorphic==0.1.10
    - django-storages==1.13.1
    - djangorestframework==3.14.0
    - djangorestframework-xml==2.0.0
    - doccano==1.8.0
    - drf-yasg==1.21.4
    - environs==9.5.0
    - et-xmlfile==1.1.0
    - fastapi==0.85.0
    - feedfinder2==0.0.4
    - feedparser==6.0.10
    - filelock==3.8.0
    - filetype==1.1.0
    - flask==2.2.2
    - flask-basicauth==0.2.0
    - flask-cors==3.0.10
    - flatbuffers==22.9.24
    - fonttools==4.37.3
    - funcy==1.17
    - furl==2.1.3
    - gevent==21.12.0
    - geventhttpclient==2.0.2
    - greenlet==1.1.3
    - gunicorn==20.1.0
    - h11==0.13.0
    - htmlmin==0.1.12
    - huggingface-hub==0.10.0
    - idna==3.4
    - importlib-metadata==4.12.0
    - inflection==0.5.1
    - iniconfig==1.1.1
    - isort==5.10.1
    - itsdangerous==2.1.2
    - itypes==1.2.0
    - jieba3k==0.35.1
    - jinja2==3.1.2
    - jmespath==1.0.1
    - joblib==1.2.0
    - jsonschema==4.16.0
    - keras==2.10.0
    - kiwisolver==1.4.4
    - kombu==5.2.4
    - langdetect==1.0.9
    - lazy-object-proxy==1.7.1
    - libclang==14.0.6
    - lml==0.1.0
    - locust==2.12.1
    - lxml==4.9.1
    - markupsafe==2.1.1
    - marshmallow==3.18.0
    - matplotlib==3.6.0
    - mccabe==0.7.0
    - msgpack==1.0.4
    - mypy-extensions==0.4.3
    - newsapi-python==0.2.6
    - newspaper3k==0.2.8
    - numpy==1.20.0
    - openpyxl==3.0.10
    - orderedmultidict==1.0.1
    - pandas==1.4.2
    - pathspec==0.10.1
    - pathtools==0.1.2
    - pillow==9.2.0
    - pkgutil-resolve-name==1.3.10
    - plac==1.1.3
    - platformdirs==2.5.2
    - protobuf==3.20.3
    - pyasn1==0.4.8
    - pycparser==2.21
    - pydantic==1.9.2
    - pydeck==0.8.0b3
    - pyexcel==0.7.0
    - pyexcel-io==0.6.6
    - pyexcel-xlsx==0.6.0
    - pyjwt==2.5.0
    - pylint==2.15.3
    - pympler==1.0.1
    - pyrsistent==0.18.1
    - pytest==7.1.3
    - pytest-cov==3.0.0
    - python-dotenv==0.21.0
    - pytz==2022.2.1
    - pytz-deprecation-shim==0.1.0.post0
    - pyyaml==5.4.1
    - pyzmq==24.0.1
    - querystring-parser==1.2.4
    - regex==2022.9.13
    - requests==2.28.1
    - requests-file==1.5.1
    - rich==12.5.1
    - roundrobin==0.0.4
    - rsa==4.9
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.6
    - s3transfer==0.6.0
    - scipy==1.8.1
    - semver==2.13.0
    - sentence-transformers==2.2.2
    - sentencepiece==0.1.97
    - sentry-sdk==1.9.9
    - seqeval==1.2.2
    - sgmllib3k==1.0.0
    - shortuuid==1.0.9
    - smart-open==6.2.0
    - smmap==5.0.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - sqlalchemy==1.4.41
    - sqlparse==0.4.3
    - srsly==1.0.5
    - starlette==0.20.4
    - streamlit==1.13.0
    - tabulate==0.8.10
    - tangled-up-in-unicode==0.2.0
    - tenacity==8.1.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-estimator==2.10.0
    - tensorflow-io-gcs-filesystem==0.27.0
    - termcolor==2.0.1
    - texttable==1.6.4
    - threadpoolctl==3.1.0
    - tinysegmenter==0.3
    - tldextract==3.3.1
    - tokenizers==0.12.1
    - toml==0.10.2
    - tomli==2.0.1
    - tomlkit==0.11.4
    - toolz==0.12.0
    - torch==1.10.2
    - tqdm==4.64.1
    - transformers
    - typing-extensions==4.3.0
    - tzdata==2022.4
    - tzlocal==4.2
    - uritemplate==4.1.1
    - urllib3==1.26.12
    - uvicorn==0.18.3
    - validators==0.20.0
    - vine==5.0.0
    - waitress==2.1.2
    - wasabi==0.10.1
    - watchdog==2.1.9
    - websocket-client==1.4.1
    - werkzeug==2.2.2
    - whitenoise==6.2.0
    - widgetsnbextension==4.0.3
    - wrapt==1.14.1
    - xxhash==3.0.0
    - zipp==3.8.1
    - zope-event==4.5.0
    - zope-interface==5.4.0